# Generated by Django 3.1.4 on 2021-01-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='batches',
            field=models.PositiveIntegerField(),
        ),
    ]
